import { Download, Copy } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

export default function ExportButton({ targetRef, filename = 'statpower-results' }) {

  const captureWithBranding = async () => {
    if (!targetRef.current) return null;
    const el = targetRef.current;

    // Step 1: Capture the content as-is (light theme, white bg)
    const contentCanvas = await html2canvas(el, {
      scale: 2,
      backgroundColor: '#ffffff',
      logging: false,
      useCORS: true,
    });

    // Step 2: Load the logo
    const logo = new Image();
    logo.crossOrigin = 'anonymous';
    logo.src = import.meta.env.BASE_URL + 'analytica-logo.png';
    await new Promise(resolve => {
      if (logo.complete) resolve();
      else { logo.onload = resolve; logo.onerror = resolve; }
    });

    // Step 3: Create final canvas with header + content + footer
    const padding = 60; // side padding
    const headerH = 80;
    const footerH = 60;
    const gap = 20;
    const totalW = contentCanvas.width + padding * 2;
    const totalH = headerH + gap + contentCanvas.height + gap + footerH;

    const final = document.createElement('canvas');
    final.width = totalW;
    final.height = totalH;
    const ctx = final.getContext('2d');

    // White background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, totalW, totalH);

    // ── Header: logo left, tagline right ──
    const logoH = 36;
    const logoW = logo.naturalWidth ? (logo.naturalWidth / logo.naturalHeight) * logoH : 100;
    ctx.drawImage(logo, padding, (headerH - logoH) / 2, logoW, logoH);

    ctx.fillStyle = '#a1a1aa';
    ctx.font = '600 16px Inter, -apple-system, sans-serif';
    ctx.textAlign = 'right';
    ctx.fillText('STATPOWER PRO', totalW - padding, headerH / 2 - 4);
    ctx.font = '400 13px Inter, -apple-system, sans-serif';
    ctx.fillText('Research Design Toolkit', totalW - padding, headerH / 2 + 16);

    // Header divider
    ctx.strokeStyle = '#e4e4e7';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(padding, headerH);
    ctx.lineTo(totalW - padding, headerH);
    ctx.stroke();

    // ── Content ──
    ctx.drawImage(contentCanvas, padding, headerH + gap);

    // ── Footer divider ──
    const footerY = headerH + gap + contentCanvas.height + gap;
    ctx.strokeStyle = '#e4e4e7';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(padding, footerY - 10);
    ctx.lineTo(totalW - padding, footerY - 10);
    ctx.stroke();

    // Footer text
    ctx.fillStyle = '#a1a1aa';
    ctx.font = '500 14px Inter, -apple-system, sans-serif';
    ctx.textAlign = 'left';
    ctx.fillText('Generated by StatPower Pro — analyticadss.com', padding, footerY + 14);

    ctx.textAlign = 'right';
    ctx.font = '400 14px Inter, -apple-system, sans-serif';
    ctx.fillText(
      new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
      totalW - padding, footerY + 14
    );

    return final;
  };

  const handleExportPDF = async () => {
    const canvas = await captureWithBranding();
    if (!canvas) return;

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: canvas.width > canvas.height ? 'landscape' : 'portrait',
      unit: 'px',
      format: [canvas.width, canvas.height],
    });

    pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
    pdf.save(`${filename}.pdf`);
  };

  const handleCopyImage = async () => {
    const canvas = await captureWithBranding();
    if (!canvas) return;

    try {
      canvas.toBlob(async (blob) => {
        await navigator.clipboard.write([
          new ClipboardItem({ 'image/png': blob })
        ]);
      });
    } catch (err) {
      console.error('Copy failed:', err);
    }
  };

  return (
    <div style={{ display: 'flex', gap: 6 }}>
      <button className="btn btn-secondary btn-sm" onClick={handleCopyImage} title="Copy to clipboard">
        <Copy size={14} />
        Copy
      </button>
      <button className="btn btn-secondary btn-sm" onClick={handleExportPDF} title="Download PDF">
        <Download size={14} />
        Export PDF
      </button>
    </div>
  );
}
