import { Download, Copy } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

const LOGO_URL = import.meta.env.BASE_URL + 'analytica-logo.png';

export default function ExportButton({ targetRef, filename = 'statpower-results' }) {

  const captureWithBranding = async () => {
    if (!targetRef.current) return null;
    const el = targetRef.current;

    // Create a wrapper with dark branded background
    const wrapper = document.createElement('div');
    wrapper.style.cssText = `
      background: #111827;
      padding: 40px 36px 32px;
      border-radius: 16px;
      position: fixed;
      left: -9999px;
      top: 0;
      width: ${el.scrollWidth + 72}px;
      font-family: Inter, -apple-system, sans-serif;
      color: #f9fafb;
    `;

    // Header with logo
    const header = document.createElement('div');
    header.style.cssText = 'display: flex; align-items: center; justify-content: space-between; margin-bottom: 28px; padding-bottom: 20px; border-bottom: 1px solid rgba(255,255,255,0.1);';

    const logo = document.createElement('img');
    logo.src = LOGO_URL;
    logo.style.cssText = 'height: 32px; opacity: 0.9;';
    logo.crossOrigin = 'anonymous';
    header.appendChild(logo);

    const tagline = document.createElement('div');
    tagline.style.cssText = 'font-size: 11px; color: rgba(255,255,255,0.4); letter-spacing: 1px; text-transform: uppercase; font-weight: 500;';
    tagline.textContent = 'StatPower Pro — Research Design Toolkit';
    header.appendChild(tagline);

    wrapper.appendChild(header);

    // Clone the content
    const clone = el.cloneNode(true);

    // Restyle the clone for dark export
    clone.style.cssText = 'background: transparent; color: #f9fafb;';

    // Fix colors in cloned elements for dark background
    const fixDarkTheme = (node) => {
      if (node.nodeType !== 1) return;
      const style = window.getComputedStyle(node);
      const bg = style.backgroundColor;
      const color = style.color;
      const border = style.borderColor;

      // Make white/light backgrounds semi-transparent
      if (bg && (bg.includes('255, 255, 255') || bg.includes('250, 250, 250') || bg.includes('244, 244, 245'))) {
        node.style.backgroundColor = 'rgba(255,255,255,0.06)';
      }
      if (bg && bg.includes('239, 246, 255')) {
        node.style.backgroundColor = 'rgba(37, 99, 235, 0.15)';
      }
      if (bg && bg.includes('219, 234, 254')) {
        node.style.backgroundColor = 'rgba(37, 99, 235, 0.2)';
      }

      // Fix dark text to light
      if (color && (color.includes('24, 24, 27') || color.includes('82, 82, 91'))) {
        node.style.color = '#f0f0f2';
      }
      if (color && color.includes('161, 161, 170')) {
        node.style.color = 'rgba(255,255,255,0.5)';
      }

      // Fix borders
      if (border && (border.includes('228, 228, 231') || border.includes('240, 240, 242'))) {
        node.style.borderColor = 'rgba(255,255,255,0.1)';
      }

      // Fix SVG text/ticks in charts
      if (node.tagName === 'text') {
        const fill = node.getAttribute('fill');
        if (fill === '#a1a1aa' || fill === '#71717a') {
          node.setAttribute('fill', 'rgba(255,255,255,0.5)');
        }
      }
      if (node.tagName === 'line' || node.tagName === 'path') {
        const stroke = node.getAttribute('stroke');
        if (stroke === '#f0f0f2' || stroke === '#e4e4e7') {
          node.setAttribute('stroke', 'rgba(255,255,255,0.08)');
        }
        if (stroke === '#a1a1aa') {
          node.setAttribute('stroke', 'rgba(255,255,255,0.3)');
        }
      }

      for (const child of node.children) fixDarkTheme(child);
    };
    fixDarkTheme(clone);

    wrapper.appendChild(clone);

    // Footer
    const footer = document.createElement('div');
    footer.style.cssText = 'margin-top: 24px; padding-top: 16px; border-top: 1px solid rgba(255,255,255,0.1); display: flex; justify-content: space-between; align-items: center;';

    const footerLeft = document.createElement('div');
    footerLeft.style.cssText = 'font-size: 10px; color: rgba(255,255,255,0.3);';
    footerLeft.textContent = `Generated by StatPower Pro — analyticadss.com`;
    footer.appendChild(footerLeft);

    const footerRight = document.createElement('div');
    footerRight.style.cssText = 'font-size: 10px; color: rgba(255,255,255,0.25);';
    footerRight.textContent = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    footer.appendChild(footerRight);

    wrapper.appendChild(footer);
    document.body.appendChild(wrapper);

    // Wait for logo to load
    await new Promise(resolve => {
      if (logo.complete) resolve();
      else { logo.onload = resolve; logo.onerror = resolve; }
    });

    try {
      const canvas = await html2canvas(wrapper, {
        scale: 2,
        backgroundColor: '#111827',
        logging: false,
        useCORS: true,
      });
      return canvas;
    } finally {
      document.body.removeChild(wrapper);
    }
  };

  const handleExportPDF = async () => {
    const canvas = await captureWithBranding();
    if (!canvas) return;

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: canvas.width > canvas.height ? 'landscape' : 'portrait',
      unit: 'px',
      format: [canvas.width, canvas.height],
    });

    pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
    pdf.save(`${filename}.pdf`);
  };

  const handleCopyImage = async () => {
    const canvas = await captureWithBranding();
    if (!canvas) return;

    try {
      canvas.toBlob(async (blob) => {
        await navigator.clipboard.write([
          new ClipboardItem({ 'image/png': blob })
        ]);
      });
    } catch (err) {
      console.error('Copy failed:', err);
    }
  };

  return (
    <div style={{ display: 'flex', gap: 6 }}>
      <button className="btn btn-secondary btn-sm" onClick={handleCopyImage} title="Copy to clipboard">
        <Copy size={14} />
        Copy
      </button>
      <button className="btn btn-secondary btn-sm" onClick={handleExportPDF} title="Download PDF">
        <Download size={14} />
        Export PDF
      </button>
    </div>
  );
}
