import { Download } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

// Preload logo for PDF stamping
const logoPromise = new Promise((resolve) => {
  const img = new Image();
  img.crossOrigin = 'anonymous';
  img.onload = () => {
    const c = document.createElement('canvas');
    c.width = img.width;
    c.height = img.height;
    c.getContext('2d').drawImage(img, 0, 0);
    resolve(c.toDataURL('image/png'));
  };
  img.onerror = () => resolve(null);
  img.src = '/logo-color.png';
});

export default function ExportButton({ targetRef, filename = 'statpower-results' }) {
  const handleExport = async () => {
    if (!targetRef.current) return;

    try {
      const canvas = await html2canvas(targetRef.current, {
        scale: 2,
        backgroundColor: '#ffffff',
        logging: false,
      });

      const pageW = canvas.width + 80; // padding
      const pageH = canvas.height + 140; // room for header + footer
      const pdf = new jsPDF({
        orientation: pageW > pageH ? 'landscape' : 'portrait',
        unit: 'px',
        format: [pageW, pageH],
      });

      // Add logo header
      const logoData = await logoPromise;
      if (logoData) {
        const logoH = 36;
        const logoW = logoH * (828 / 498); // maintain aspect ratio
        pdf.addImage(logoData, 'PNG', 40, 24, logoW, logoH);
      }

      // Add content
      const imgData = canvas.toDataURL('image/png');
      pdf.addImage(imgData, 'PNG', 40, 76, canvas.width, canvas.height);

      // Add footer
      pdf.setFontSize(9);
      pdf.setTextColor(160, 160, 170);
      pdf.text('Generated by StatPower Pro — analyticadss.com', 40, pageH - 20);
      pdf.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pageW - 40, pageH - 20, { align: 'right' });

      pdf.save(`${filename}.pdf`);
    } catch (err) {
      console.error('Export failed:', err);
    }
  };

  return (
    <button className="btn btn-secondary btn-sm" onClick={handleExport}>
      <Download size={14} />
      Export PDF
    </button>
  );
}
